apiVersion: v1 # versi API inti yang berisi banyak resource paling umum seperti Pod dan Node
kind: Secret # jenis resource yang didefinisikan
metadata:
  name: mongo-secret # nama resource
data: # informasi env dalam bentuk base64
  MONGO_ROOT_USERNAME: YWRtaW4=
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==