apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: "kube-state-metrics"
        static_configs:
          - targets: ["kube-state-metrics.monitoring.svc.cluster.local:8080"]
      - job_name: "kubelet"
        scheme: https
        tls_config:
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
        - role: node
        relabel_configs:
        - action: replace
          source_labels: [__meta_kubernetes_node_address_InternalIP]
          target_label: __address__
          replacement: $1:10250
        metric_relabel_configs:
        - source_labels: [__name__]
          regex: "container_fs_.*|container_network_.*"
          action: drop
