name: CI Pipeline Karsajobs-Backend

on:
  push:
    branches: [ "karsajobs" ]

env:
  USERNAME: ${{ github.actor }}
  REPOSITORY_NAME: ${{ github.repository }}
  
jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  test-app:
    needs: lint-dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
  
      - name: Test
        run: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    needs: test-app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: $USERNAME
          password: ${{ secrets.TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/$REPOSITORY_NAME:latest .
          docker push ghcr.io/$REPOSITORY_NAME:latest
