name: CI Pipeline Karsajobs-Backend

on:
  push:
    branches: [ "karsajobs" ]

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install hadolint
        run: |
          wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x /bin/hadolint

      - name: Lint Dockerfile
        run: hadolint ./Dockerfile

  test-app:
    needs: lint-dockerfile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Test
      run: go test -v -short --count=1 $(go list ./...)
